Controllers/BlogPostsController.cs
using System;
using PagedList;
using PagedList.Mvc;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KerryDPeay_Blog.Helpers;
using KerryDPeay_Blog.Models;
using System.Xml.Linq;

namespace KerryDPeay_Blog.Controllers
{
    [RequireHttps]
    [Authorize(Roles = "Admin")] //To access these posts, you must be logged in as an Administrator 
    public class BlogPostsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: BlogPosts
        [AllowAnonymous]
        public ActionResult Index(int? page, string searchStr)
        {
            ViewBag.Search = searchStr;
            var blogList = IndexSearch(searchStr);

            int pageSize = 5; // the number of posts you want to display per page             
            int pageNumber = (page ?? 1);

            return View(blogList.ToPagedList(pageNumber, pageSize)); //Lists all of the posts in the order they were created (descending order)
        }

        public IQueryable<BlogPost> IndexSearch(string searchStr)
        {
            IQueryable<BlogPost> result = null;

            if (searchStr != null) {
                result = db.BlogPosts.AsQueryable();
                result = result.Where(p => p.Title.Contains(searchStr) || 
                p.Body.Contains(searchStr) || p.Comments.Any(c => c.Body.Contains(searchStr) || 
                c.Author.FirstName.Contains(searchStr) || c.Author.LastName.Contains(searchStr) || 
                c.Author.DisplayName.Contains(searchStr) || c.Author.Email.Contains(searchStr)));
            }
            else
            {
                result = db.BlogPosts.AsQueryable();
            }

            return result.OrderByDescending(p => p.Update);
        }

        [AllowAnonymous]
        public ActionResult AllPosts()
        {
            return View(db.BlogPosts.Where(b => b.Published).ToList());
        }
        public ActionResult AdminIndex()
        {
            var publishedBlogPosts = db.BlogPosts.ToList();
            return View("Index", publishedBlogPosts);

        }

        public ActionResult ModeratorIndex()
        {
            var publishedBlogPosts = db.BlogPosts.ToList();
            return View("Index", publishedBlogPosts);
        }

        /*
        // GET: BlogPosts/Details/5
        [AllowAnonymous]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            BlogPost blogPost = db.BlogPosts.Find(id);

            if (blogPost == null)
            {
                return HttpNotFound();
            }

            return View(blogPost);
        }
        */

        [AllowAnonymous]
        // GET: BlogPosts/Details/5
        public ActionResult Details(string Slug)
        {
            if (String.IsNullOrWhiteSpace(Slug))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var blogPost = db.BlogPosts.FirstOrDefault(p => p.Slug == Slug);

            if (blogPost == null)
            {
                return HttpNotFound();
            }
            return View(blogPost);
        }



        // GET: BlogPosts/Create - This action (Http:Get) is returning a View to the Creation page.
        public ActionResult Create()
        {
            return View();
        }

        // POST: BlogPosts/Create - This action (Http:Post) allows the user to create data from the View and send it to the database. 
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,Abstract,Body,MediaURL,Published")] BlogPost blogPost, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                var Slug = StringUtilities.MakeSlug(blogPost.Title);

                if (String.IsNullOrWhiteSpace(Slug))
                {
                    ModelState.AddModelError("Title", "Invalid title");
                    return View(blogPost);
                }

                if (db.BlogPosts.Any(p => p.Slug == Slug))
                {
                    ModelState.AddModelError("Title", "The title must be unique");
                    return View(blogPost);
                }

                if (String.IsNullOrWhiteSpace(Slug))
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                if (ImageUploadValidator.IsWebFriendlyImage(image))
                {
                    var fileName = Path.GetFileName(image.FileName);
                    image.SaveAs(Path.Combine(Server.MapPath("~/Uploads/"), fileName));
                    blogPost.MediaURL = "/Uploads/" + fileName;
                }

                var localDate = DateTime.UtcNow.AddHours(-4);

                blogPost.Slug = Slug; //Creates a new slug and stores it in a variable
                blogPost.Create = localDate;//Stores the time in which the post is created. 
                //blogPost.Create = myTime;
                db.BlogPosts.Add(blogPost); //Adds the current post to the collection of posts. 
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(blogPost);
        }

   

        // GET: BlogPosts/Edit/5 - Returns the Edit View only for a particular post. This Action (Http:Get) searches for the post in the 
        //database. 
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
            BlogPost blogPost = db.BlogPosts.Find(id);

            if (blogPost == null)
            {
                return HttpNotFound();
            }
            return View(blogPost);
        }

        // POST: BlogPosts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,Abstract,Body,MediaURL,Published")] BlogPost blogPost, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                var newSlug = StringUtilities.MakeSlug(blogPost.Title);

                if (newSlug != blogPost.Slug) //The slug is used to compare posts. If there is a matching slug in the collection, the user must pick a new title.
                {
                    if (String.IsNullOrWhiteSpace(newSlug))
                    {
                        ModelState.AddModelError("Title", "Invalid Title");
                        return View(blogPost);
                    }

                    if (db.BlogPosts.Any(p => p.Slug == newSlug))
                    {
                        //ModelState.AddModelError("Title", "The title must be unique");
                        blogPost.Slug = newSlug;
                        //return View(blogPost);
                    }

                    blogPost.Slug = newSlug; //The new slug, formed from the new title selected by the user becomes the current slug for the post, replacing the former one.  
                }

                if (ImageUploadValidator.IsWebFriendlyImage(image))
                {
                    var fileName = Path.GetFileName(image.FileName);
                    image.SaveAs(Path.Combine(Server.MapPath("~/Uploads/"), fileName));
                    blogPost.MediaURL = "/Uploads/" + fileName;
                }

                var localDate = DateTime.UtcNow.AddHours(-4);

                blogPost.Update = localDate;
                db.Entry(blogPost).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(blogPost);
        }

        // GET: BlogPosts/Delete/5 - Returns the select post from the database for the user to delete (or not).
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            BlogPost blogPost = db.BlogPosts.Find(id);

            if (blogPost == null)
            {
                return HttpNotFound();
            }
            return View(blogPost);
        }

        // POST: BlogPosts/Delete/5 - This action allows the user to delete the post from the database.
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BlogPost blogPost = db.BlogPosts.Find(id);
            db.BlogPosts.Remove(blogPost);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/HomeController.cs
using KerryDPeay_Blog.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net.Mail;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace KerryDPeay_Blog.Controllers
{
    [RequireHttps]
    public class HomeController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        public ActionResult Index(int? page)
        {
            int pageSize = 3; // display three blog posts at a time on this page
            int pageNumber = (page ?? 1);

            var publishedPosts = db.BlogPosts.Where(b => b.Published).OrderByDescending(b => b.Create);
            return View(publishedPosts.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            EmailModel model = new EmailModel();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Contact(EmailModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var from = model.FromName + "," + $"{model.FromEmail}<{ConfigurationManager.AppSettings["emailto"]}>"; //THe name and address of the person who entered it.

                    var email = new MailMessage(from, ConfigurationManager.AppSettings["emailto"])
                    {
                        Subject = model.Subject, //The subject of the email.
                        Body = model.Body, //The body of the email.
                        IsBodyHtml = true
                    };
                    var svc = new PersonalEmail();
                    await svc.SendAsync(email);

                    return View(new EmailModel());
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                    await Task.FromResult(0);
                }
            }
            return View(model);
            //Console.WriteLine("Message has been sent");
            //return View("Index", "BlogPosts"); //Does not work
        }
    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@model KerryDPeay_Blog.Models.EmailModel

<head>
    <style>

        #scale {
            background: url(https://cdn.shopify.com/s/files/1/0010/0994/2575/products/2066-70-lightblue_0e38026d-498a-45d9-8dcb-5f05f37baa9f_2000x.png?v=1549120526);
            background-repeat: no-repeat;
            background-size: 3000px 3000px;
        }

        .center {
            display: block;
            margin-left: auto;
            margin-right: auto;
            width: 50%;
        }

        .container {
            position: relative;
            text-align: center;
            color: white;
        }

        .centered {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
        }

        ul {
            list-style-type: none;
            margin: 0;
            padding: 0;
            overflow: hidden;
            background-color: #0000FF;
        }

        li {
            float: left;
        }

            li a {
                display: block;
                color: white;
                text-align: center;
                padding: 14px 16px;
                text-decoration: none;
            }

                li a:hover {
                    background-color: #111;
                }

             body, html {
            height: 100%;
            margin: 0;
            font-family: Arial, Helvetica, sans-serif;
        }

        .hero-image {
            background-image: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url("https://colorlib.com/wp/wp-content/uploads/sites/2/wordpress-contact-form-plugins.png");
            height: 50%;
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
            position: relative;
        }

        .hero-text {
            text-align: center;
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            color: white;
        }

            .hero-text button {
                border: none;
                outline: 0;
                display: inline-block;
                padding: 10px 25px;
                color: black;
                background-color: #ddd;
                text-align: center;
                cursor: pointer;
            }

                .hero-text button:hover {
                    background-color: #555;
                    color: white;
                }

               .button2 {border-radius: 12px;}
    </style>
</head>

<div class="hero-image">
    <div class="hero-text">
        <h1><b>Contact Me</b></h1>
    </div>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<body id="scale">

    @if (User.IsInRole("Admin"))
    {
        <!--Navbar-->
        <ul>
            <li><a class="active" href="@Url.Action("Index", "BlogPosts")">Home</a></li>
            <li><a href="@Url.Action("LogOff", "Account")">Logout</a></li>
            <li><a href="@Url.Action("Contact", "Home")">Contact Me</a></li>
            <li><a href=@Url.Action("AllPosts", "BlogPosts")>Old Posts</a></li>
            <li><a href=@Url.Action("Create", "BlogPosts")>Create Post</a></li>
        </ul>
    }

    @if ((User.Identity.IsAuthenticated) && !(User.IsInRole("Admin")))
    {
        <!--Navbar-->
        <ul>
            <li><a class="active" href="@Url.Action("Index", "BlogPosts")">Home</a></li>
            <li><a href="@Url.Action("LogOff", "Account")">Logout</a></li>
            <li><a href="@Url.Action("Contact", "Home")">Contact Me</a></li>
            <li><a href=@Url.Action("AllPosts", "BlogPosts")>Old Posts</a></li>
        </ul>
    }

    @if (!(User.Identity.IsAuthenticated))
    {
        <!--Navbar-->

        <ul>
            <li><a class="active" href="@Url.Action("Index", "BlogPosts")">Home</a></li>
            <li><a href="@Url.Action("Login", "Account")">Login</a></li>
            <li><a href="@Url.Action("Contact", "Home")">Contact Me</a></li>
            <li><a href=@Url.Action("AllPosts", "BlogPosts")>Old Posts</a></li>
        </ul>
    }

    @Html.ValidationSummary("", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(m => m.FromName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.FromName, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.FromName)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.FromEmail, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.FromEmail, new { @class = "form-control", placeholder = "example@email.com" })
            @Html.ValidationMessageFor(m => m.FromEmail)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Subject, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Subject, new { @class = "form-control", placeholder = "Enter subject here" })
            @Html.ValidationMessageFor(m => m.Subject)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Body, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Body, new { @class = "form-control", placeholder = "Enter a message", id = "editor" })
            @Html.ValidationMessageFor(m => m.Body)
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-primary" value="Send" />
        </div>
    </div>

    <br />

    <div>
        <button class="btn btn-default">@Html.ActionLink("Back to Homepage", "Index", "BlogPosts")</button>
    </div>

</body>

    <hr />

}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script src="~/Scripts/tinymce/tinymce.min.js"></script>
    <script src="~/Scripts/tinymce/jquery.tinymce.min.js"></script>

    <script type="text/javascript">
        tinymce.init({
            selector: '#editor'
        });
    </script>
}

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>